<?php

$router->get('/', 'index.php')->only('auth');
$router->get('/product', 'products/product.php');
$router->get('/register','registration/create.php');
$router->post('/register','registration/store.php');
$router->get('/login','sessions/create.php');
$router->post('/sessions','sessions/store.php');
$router->delete('/sessions','sessions/destroy.php')->only('auth');
$router->get('/product/create','products/create.php');
$router->post('/product','products/store.php');
$router->delete('/product','products/destroy.php');
$router->get('/product/edit','products/edit.php');
$router->patch('/product', 'products/update.php');
$router->get('/customer', 'customers/index.php');
$router->get('/customer/create','customers/create.php');
$router->post('/customer','customers/store.php');
$router->get('/customer/edit','customers/edit.php');
$router->patch('/customer','customers/update.php');
$router->delete('/customer','customers/destroy.php');
$router->get('/image', 'images/index.php');
$router->get('/order', 'orders/index.php');
$router->get('/order/create', 'orders/create.php');
$router->post('/order','orders/store.php');
$router->get('/order/edit','orders/edit.php');
$router->patch('/order/update','orders/update.php');
$router->delete('/order','orders/destroy.php');
$router->get('/employee','employees/index.php');
$router->get('/employee/create','employees/create.php');
$router->post('/employee','employees/store.php');
